-- Disable RLS on all core tables to allow public access
ALTER TABLE staff DISABLE ROW LEVEL SECURITY;
ALTER TABLE availability DISABLE ROW LEVEL SECURITY;
ALTER TABLE task_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE managers DISABLE ROW LEVEL SECURITY;
ALTER TABLE manager_availability DISABLE ROW LEVEL SECURITY;
ALTER TABLE rotas DISABLE ROW LEVEL SECURITY;
ALTER TABLE rota_backups DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log DISABLE ROW LEVEL SECURITY;